services:
  proxy:
    build: ./proxy
    ports:
      - ${PORT}:80

  frontend:
    build: ./frontend

  backend:
    build: ./backend
    volumes:
      - ./backend/prisma/database.db:/app/prisma/database.db
